workflows:
  expo-android:
    name: Build Expo APK
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: latest
      npm: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Expo Android APK
        script: |
          npx expo build:android -t apk --non-interactive

    artifacts:
      - dist/*.apk

    publishing:
      email:
        recipients:
          - ashithaj4321@gmail.com