workflows:
  expo-android:
    name: Expo Android (EAS)
    max_build_duration: 60

    environment:
      node: latest
      npm: latest
      vars:
        CI: "1"            # fixes "--non-interactive is not supported"
        EXPO_TOKEN: Encrypted(EXPO_TOKEN)   # set this in Environment variables tab

    scripts:
      # 1. Install dependencies
      - npm install

      # 2. Install EAS CLI (if not already in devDependencies)
      - npm install -g eas-cli

      # 3. Build Android app with EAS
      - eas build --platform android --profile preview

    artifacts:
      # Codemagic will automatically collect build artifacts,
      # this is just a fallback – keep it as is
      - "**/*.apk"
      - "**/*.aab"