workflows:
  android_apk:
    name: Build Android APK (Expo prebuild)
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      node: 20
      npm: 10
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Generate android project from Expo
        script: |
          npx expo prebuild --platform android --non-interactive

      - name: Build release APK with Gradle
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk